version: 2.1

orbs:
  docker: circleci/docker@2.2.0

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: ahmadsherief/simple-node-ci
          tag: "ahmadsherief/simple-node-ci:latest"
