version: 2.1

orbs:
  # node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          before_build:
            - run:
                command: echo "Did this before the build" && echo $CIRCLE_PROJECT_USERNAME && echo $DOCKERHUB_USERNAME
                name: Do this before the build
          image: $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME
          tag: "v1.1"
# Define the jobs we want to run for this project
# jobs:
#   - docker/publish:
#       before_build:
#         - run:
#             command: echo "Did this before the build"
#             name: Test lifecycle hooks
#       image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

# # Orchestrate our job run sequence
# workflows:
#   build_and_publish:
#     jobs:
#       - docker/publish
